[tasks.publish]
run = "cargo publish"

[tasks.run]
extends = "rust:run"

[tasks.clean]
extends = "rust:clean"

[tasks.build]
extends = "rust:build"

[tasks.check]
extends = "rust:check"

[tasks.format]
extends = "rust:format"
