install:
	npm install

clean:
  rm -rf coverage dist 

@schema:
  flatc --ts -o ./src/__generated__ ../flatbuffers/service.fbs ../flatbuffers/enums.fbs

build: install
  npm run build

@test: install
  just ../cli/build
  RUNTIME_ENV=test npm run test

publish: install
	npm publish
