// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type POS = int8
const (
	POSverb POS = 0
	POSnoun POS = 1
	POSadj POS = 2
	POSpronoun POS = 3
	POSadv POS = 4
	POSprep POS = 5
	POSconj POS = 6
	POSintj POS = 7
	POSprefix POS = 8
	POSsuffix POS = 9
	POSparticle POS = 10
)

var EnumNamesPOS = map[POS]string{
	POSverb:"verb",
	POSnoun:"noun",
	POSadj:"adj",
	POSpronoun:"pronoun",
	POSadv:"adv",
	POSprep:"prep",
	POSconj:"conj",
	POSintj:"intj",
	POSprefix:"prefix",
	POSsuffix:"suffix",
	POSparticle:"particle",
}

