# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    - go work sync

dist: bin 

builds:
  - id: all
    main: ./odict.go
    binary: 'odict-{{.Os}}-{{.Arch}}'
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    goos:
      - linux
      - darwin
      - windows 
    no_unique_dist_dir: true 
  - id: single
    main: ./odict.go
    binary: odict
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    no_unique_dist_dir: true 

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip