before:
  hooks:
    - go work sync

dist: bin 
 
project_name: odict

git:
  ignore_tags:
    - js-*
    - python-*
    - jvm-*

env:
  - CGO_ENABLED=1

builds:
  - id: darwin
    binary: odict
    main: ./odict.go
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    goos:
      - darwin
    flags:
      - -trimpath
  - id: windows
    binary: odict
    main: ./odict.go
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    goos:
      - windows
    flags:
      - -trimpath
  - id: linux
    binary: odict
    main: ./odict.go
    ldflags:
      - -X 'github.com/TheOpenDictionary/odict/cli.version={{.Version}}'
    goos:
      - linux
    flags:
      - -trimpath
    overrides:
      - goos: linux 
        goarch: arm64 
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux 
        goarch: amd64 
        env:
          - CC=gcc

archives:
  - builds:
      - darwin
      
brews:
  - name: odict
    homepage: "https://odict.org/"
    description: "A lightning-fast dictionary compiler and toolchain"
    folder: Formula
    repository:
      owner: TheOpenDictionary
      name: homebrew-odict
      token: "{{ .Env.HOMEBREW_GH_TOKEN }}"