version: '3'
services:
  builder:
    build: .
    ports:
      - "8080:80"
    environment:
      CGO_ENABLED: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/go/src/odict
      - ./sysroot:/sysroot
    working_dir: /go/src/odict
    command: build --snapshot --clean
