experimental_monorepo_root = true

[env]
MISE_EXPERIMENTAL = 1
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"

[tools]
"cargo:cargo-nextest" = "0.9.92"
"cargo:cargo-dist" = "0.31.0"
"cargo:cargo-insta" = "1.42.2"
"cargo:cargo-edit" = "latest"
rust = "latest"
zig = "latest"
hk = "latest"
"npm:astro" = "latest"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"
ruff = "latest"
taplo = "latest"
rumdl = "latest"

[monorepo]
config_roots = ["crates/*", "node", "python", "cli", "docs"]

[task_templates."rust:check"]
description = "Lints the project"
run = "cargo clippy --manifest-path Cargo.toml --all-features"

[task_templates."rust:build"]
run = "cargo build"
sources = ["src/**/*.rs", "Cargo.toml"]
outputs = { auto = true }

[task_templates."rust:run"]
run = "cargo run --release"
sources = ["src/**/*.rs", "Cargo.toml"]
outputs = { auto = true }

[task_templates."rust:clean"]
run = "cargo clean"

[task_templates."rust:format"]
run = "cargo fmt"
sources = ["src/**/*.rs"]
outputs = { auto = true }

[settings]
python.uv_venv_auto = true
lockfile = true

[tasks.run]
run = "cargo run --release -p odict-cli --"

[tasks.build]
run = "cargo build -p odict-cli"

[tasks.clean]
run = "cargo clean"
description = "Removes all Rust build artifacts via Cargo"

[tasks."clean:all"]
run = "git clean -xdf"
description = "Recursively cleans all packages in the project"

[tasks."snapshot"]
run = "cargo insta accept"
description = "Updates all Insta snapshot tests"

[tasks.bench]
run = "cargo bench"
description = "Runs benchmarks for all Cargo packages"

[tasks.why]
run = "cargo tree -i"

[tasks.check]
depends = ["//...:check"]

[tasks.docgen]
run = "cargo run --release -p docgen"

[tasks.fix]
depends = ["//...:fix"]
run = "cargo clippy --all-targets --all-features --fix --allow-dirty -- -D warnings"

[tasks."test"]
run = "cargo nextest run -p odict-cli -p odict -p internal --all-features --verbose"
description = "Runs nextest on all Cargo packages"

[tasks."test:all"]
depends = ["//...:test"]
description = "Recursively tests all packages in the project"

[tasks."up"]
depends = ["//...:up"]
run = "cargo upgrade"
description = "Updates all dependencies to their latest versions"

[tasks."build:all"]
depends = ["//...:build"]
description = "Recursively builds all packages in the project"

[tasks."format:markdown"]
run = "rumdl fmt **/*.md"

[tasks."format:toml"]
run = "taplo format **/*.toml"

[tasks."format:mise"]
run = "mise fmt --all"

[tasks."format"]
depends = [
  "//...:format",
  "//:format:toml",
  "//:format:mise",
  "//:format:markdown",
]

[tasks."ci"]
run = 'mise x act@latest -- act {{arg(name="workflow", default="ci")}} --container-architecture linux/amd64 --bind --job {{arg(name="job_id")}}'
hide = true
