INSERT INTO dictionaries (name, id) VALUES ('Example Dictionary 1', 1);
INSERT INTO entries (id, term, dictionary_id) VALUES (1, 'ran', 1);
INSERT INTO entries (id, term, dictionary_id) VALUES (2, 'run', 1);
INSERT INTO etymologies (id, description, entry_id) VALUES (1, 'Latin root', 2);
INSERT INTO senses (id, etymology_id) VALUES (1, 1);
INSERT INTO senses (id, etymology_id) VALUES (2, 1);
INSERT INTO groups (id, description, sense_id) VALUES (1, 'A number of verb senses', 2);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (1, '(vertebrates) To move swiftly (figuratively)', 2, 1);
INSERT INTO definition_examples (id, text, definition_id) VALUES (1, 'The dog runs after the cat.', 1);
INSERT INTO definition_examples (id, text, definition_id) VALUES (2, 'The horse ran away.', 1);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (2, '(fluids) To flow.', 2, 1);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (3, '(nautical, of a vessel) To sail before the wind, in distinction from reaching or sailing close-hauled.', 2, 1);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (4, '(social) To carry out an activity.', 2, 1);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (5, 'To extend or persist, statically or dynamically, through space or time.', 2, 1);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (6, '(transitive) To execute or carry out a plan, procedure or program.', 2, 1);
INSERT INTO entries (id, term, dictionary_id) VALUES (3, 'cat', 1);
INSERT INTO etymologies (id, description, entry_id) VALUES (2, 'Latin root', 3);
INSERT INTO senses (id, etymology_id) VALUES (3, 2);
INSERT INTO entries (id, term, dictionary_id) VALUES (4, 'dog', 1);
INSERT INTO etymologies (id, description, entry_id) VALUES (3, 'Latin root', 4);
INSERT INTO senses (id, etymology_id) VALUES (4, 3);
INSERT INTO entries (id, term, dictionary_id) VALUES (5, 'poo', 1);
INSERT INTO etymologies (id, description, entry_id) VALUES (4, 'Latin root', 5);
INSERT INTO senses (id, etymology_id) VALUES (5, 4);
INSERT INTO groups (id, description, sense_id) VALUES (2, 'A number of verb senses', 5);
INSERT INTO definitions (id, text, sense_id, group_id) VALUES (7, 'crap, shit', 5, 2);
