// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Etymology extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Etymology getRootAsEtymology(ByteBuffer _bb) { return getRootAsEtymology(_bb, new Etymology()); }
  public static Etymology getRootAsEtymology(ByteBuffer _bb, Etymology obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Etymology __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String description() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public schema.Usage usages(int j) { return usages(new schema.Usage(), j); }
  public schema.Usage usages(schema.Usage obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int usagesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public schema.Usage usagesByKey(byte key) { int o = __offset(8); return o != 0 ? schema.Usage.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public schema.Usage usagesByKey(schema.Usage obj, byte key) { int o = __offset(8); return o != 0 ? schema.Usage.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public schema.Usage.Vector usagesVector() { return usagesVector(new schema.Usage.Vector()); }
  public schema.Usage.Vector usagesVector(schema.Usage.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createEtymology(FlatBufferBuilder builder,
      int idOffset,
      int descriptionOffset,
      int usagesOffset) {
    builder.startTable(3);
    Etymology.addUsages(builder, usagesOffset);
    Etymology.addDescription(builder, descriptionOffset);
    Etymology.addId(builder, idOffset);
    return Etymology.endEtymology(builder);
  }

  public static void startEtymology(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(1, descriptionOffset, 0); }
  public static void addUsages(FlatBufferBuilder builder, int usagesOffset) { builder.addOffset(2, usagesOffset, 0); }
  public static int createUsagesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUsagesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endEtymology(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Etymology get(int j) { return get(new Etymology(), j); }
    public Etymology get(Etymology obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

