// automatically generated by the FlatBuffers compiler, do not modify

package schema;

public final class POS {
  private POS() { }
  public static final byte v = 0;
  public static final byte n = 1;
  public static final byte adj = 2;
  public static final byte pro = 3;
  public static final byte adv = 4;
  public static final byte prep = 5;
  public static final byte conj = 6;
  public static final byte intj = 7;
  public static final byte pref = 8;
  public static final byte suff = 9;
  public static final byte part = 10;
  public static final byte art = 11;
  public static final byte un = 12;

  public static final String[] names = { "v", "n", "adj", "pro", "adv", "prep", "conj", "intj", "pref", "suff", "part", "art", "un", };

  public static String name(int e) { return names[e]; }
}

