[tools]
node = "24.11.1"
"npm:corepack" = "latest"

[deps.yarn]
auto = true

[tasks.prepare]
run = ["corepack enable", "yarn install"]
sources = ["package.json"]
outputs = { auto = true }

[tasks."build:node"]
depends = [":prepare"]
alias = "build"
env = { "AWS_LC_SYS_NO_JITTER_ENTROPY" = 1 }
run = "yarn build:node"

[tasks."create-dirs"]
depends = [":prepare"]
run = "yarn create-dirs"

[tasks.artifacts]
depends = [":prepare"]
run = "yarn artifacts"

[tasks."build:wasm"]
depends = [":prepare"]
run = ["yarn build:wasm"]

[tasks.lint]
depends = [":prepare"]
run = "yarn lint"

[tasks."dev:wasm"]
depends = [":prepare", ":build:wasm"]
run = "yarn dev:wasm"

[tasks.upgrade]
depends = [":prepare"]
run = "yarn up"

[tasks.publish]
depends = [":prepare"]
run = "npm publish"

[tasks.test]
depends = [":build"]
run = "yarn test"

[tasks.snapshot]
depends = [":test -u"]

[tasks.ci]
run = 'mise x act@latest -- act napi --container-architecture linux/amd64 --bind --job {{arg(name="job_id")}}'
hide = true
