VENV_DIR := ".venv"

_maturin +args:
  {{VENV_DIR}}/bin/maturin {{args}}

@develop: (_maturin "develop")

@build: (_maturin "build")

@test:
  {{VENV_DIR}}/bin/pytest

@setup:
  python -m venv {{VENV_DIR}}
  sh {{VENV_DIR}}/bin/activate
  {{VENV_DIR}}/bin/pip install -r requirements-dev.txt

