[private]
copy-exec:
  mkdir -p ./src/__generated__ && cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./src/__generated__/

install:
  npm install 

build: copy-exec install
  GOOS=js GOARCH=wasm go build -o ./src/odict.wasm ./src/main.go && npm run build