[private]
@copy-exec:
  cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./src

[private]
@wasm:
  mkdir -p dist
  GOOS=js GOARCH=wasm go build -o ./src/odict.wasm ./src/odict.go && cp ./src/odict.wasm ./dist/odict.wasm

@install:
  npm install 

@preview: build
  cp ./src/odict.wasm ./.preview/odict.wasm
  npx parcel --dist-dir=.preview demo.html --open

@clean:
  rm -rf ../**/*.odict 

@test: copy-exec install wasm && clean
  npx tsc && npx jest --detectOpenHandles

@build: copy-exec install wasm
  just ../js/schema
  cp -r ../js/src/types.ts ../js/src/__generated__ ./src
  npx concurrently "swc -d dist ./src/*.{ts,js} ./src/**/*.{ts,js}" "tsc"