["setup:wasm"]
run = "pnpm install"
sources = ["${MISE_TASK_DIR}/package.json"]
outputs = { auto = true }

["build:wasm"]
depends = ["setup:node"]
run = "pnpm --filter=\"@odict/wasm\" build"

["dev:wasm"]
depends = ["build:wasm"]
run = "pnpm --filter=\"@odict/wasm\" dev"
