@schema:
	flatc -g --gen-onefile --go-namespace types -o ./types ../flatbuffers/schema.fbs ../flatbuffers/enums.fbs && goimports -w ./types/*.go

test:
  just ../cli/build
  go test -ldflags "-X 'github.com/TheOpenDictionary/odict/cli.version=$(cat ../version.txt)'" ./**/