@schema:
	flatc -g --gen-onefile --go-namespace types -o ./types ../schema.fbs

test:
  just ../cli/build
  go test -ldflags "-X 'github.com/TheOpenDictionary/odict/cli.version=$(cat ../version.txt)'" ./**/