// automatically generated by the FlatBuffers compiler, do not modify

export enum ODictMethod {
  Lookup = 1,
  Split = 2,
  Index = 3,
  Search = 4,
  Compile = 5,
  Write = 6,
  Lexicon = 7,
  Load = 8
}
