// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class WritePayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WritePayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWritePayload(bb:flatbuffers.ByteBuffer, obj?:WritePayload):WritePayload {
  return (obj || new WritePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWritePayload(bb:flatbuffers.ByteBuffer, obj?:WritePayload):WritePayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WritePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

xml():string|null
xml(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
xml(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

out():string|null
out(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
out(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startWritePayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addXml(builder:flatbuffers.Builder, xmlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, xmlOffset, 0);
}

static addOut(builder:flatbuffers.Builder, outOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, outOffset, 0);
}

static endWritePayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWritePayload(builder:flatbuffers.Builder, xmlOffset:flatbuffers.Offset, outOffset:flatbuffers.Offset):flatbuffers.Offset {
  WritePayload.startWritePayload(builder);
  WritePayload.addXml(builder, xmlOffset);
  WritePayload.addOut(builder, outOffset);
  return WritePayload.endWritePayload(builder);
}
}
