[package]
edition = "2024"
name = "odict_node"
version = "0.0.2"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["search", "json", "sql", "tokenize"]
json = ["odict/json"]
tokenize = ["odict/tokenize-all"]
sql = ["odict/sql"]
config = ["odict/config"]
search = ["odict/search", "config"]

[dependencies]
merge = "0.1.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"
odict = { path = "../lib" }

[build-dependencies]
napi-build = "2.0.1"
