[package]
edition = "2024"
name = "odict_node"
version = "0.0.2"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
merge = "0.1.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "3.0.0-alpha.33", default-features = false, features = ["napi4"] }
napi-derive = "3.0.0-alpha.29"
odict = { path = "../lib", features = ["config", "sql", "search", "json"] }

[build-dependencies]
napi-build = "2.0.1"
