[package]
edition = "2021"
name = "odict_node"
version = "1.1.1"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["search", "sql", "tokenize"]
tokenize = [
  "odict/tokenize-latin",
  "odict/tokenize-chinese",
  "odict/tokenize-thai",
  "odict/tokenize-khmer",
  "odict/tokenize-swedish",
  "odict/tokenize-german",
]
sql = ["odict/sql"]
config = ["odict/config"]
search = ["odict/search", "config"]

[dependencies]
merge = "0.2.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"
odict = { path = "../lib" }
structural-convert = { workspace = true }
internal = { path = "../internal" }

[build-dependencies]
napi-build = "2.0.1"
