@deps: install
  
@install:
  pnpm install --no-frozen-lockfile

@add +args:
  pnpm add {{args}}

@npm +args:
  pnpm npm {{args}}

@clean:
  rm -rf coverage ../**/*.odict  ../**/*.log

@build:
  pnpm build 

@universal: 
  pnpm universal

@version:  
  pnpm version

@test: build && clean
  pnpm test

@publish +args="":
	just npm publish {{args}}

[private]
local-ci +args="":
  cd .. && act napi --container-architecture linux/amd64 --job build {{args}}