@deps: 
  pnpm install

@add +args:
  pnpm add {{args}}

@npm +args:
  pnpm npm {{args}}

@clean:
  rm -rf coverage ../**/*.odict  ../**/*.log

@build:
  pnpm build 

@universal: 
  pnpm universal

@version:  
  pnpm version

@test: build && clean
  pnpm test

@publish +args="":
	just npm publish {{args}}