/* auto-generated by NAPI-RS */
/* eslint-disable */

/** The WASI flavor this loader instantiates. */
export declare const __napiBindingTarget: "wasm32-wasi";

export declare class OpenDictionary {
  constructor(data: Buffer);
  get minRank(): number | null;
  get maxRank(): number | null;
  lookup(
    query: string | Array<string>,
    options?: LookupOptions | undefined | null,
  ): Array<LookupResult>;
  split(
    query: string | Array<string>,
    options?: SplitOptions | undefined | null,
  ): Array<LookupResult>;
  lexicon(): Array<string>;
  tokenize(text: string, options?: TokenizeOptions | undefined | null): Array<Token>;
}

export declare function compile(xml: string): Buffer;

export interface Definition {
  id?: string;
  value: string;
  examples: Array<Example>;
  notes: Array<Note>;
}

export interface Entry {
  term: string;
  rank?: number;
  seeAlso?: string;
  etymologies: Array<Etymology>;
  media: Array<MediaURL>;
}

export interface EnumWrapper {
  name: string;
  variant: string;
  value: string;
}

export interface Etymology {
  id?: string;
  pronunciations: Array<Pronunciation>;
  description?: string;
  senses: Array<Sense>;
}

export interface Example {
  value: string;
  translations: Array<Translation>;
  pronunciations: Array<Pronunciation>;
}

export interface Form {
  term: string;
  kind?: EnumWrapper;
  tags: Array<string>;
}

export interface Group {
  id?: string;
  description: string;
  definitions: Array<Definition>;
}

export interface LookupOptions {
  split?: number;
  follow?: boolean;
  insensitive?: boolean;
}

export interface LookupResult {
  entry: Entry;
  directedFrom?: Entry;
}

export interface MediaUrl {
  src: string;
  mimeType?: string;
  description?: string;
}

export interface Note {
  id?: string;
  value: string;
  examples: Array<Example>;
}

export interface Pronunciation {
  kind?: EnumWrapper;
  value: string;
  media: Array<MediaUrl>;
}

export interface Sense {
  pos: EnumWrapper;
  lemma?: string;
  definitions: Array<Definition | Group>;
  tags: Array<string>;
  translations: Array<Translation>;
  forms: Array<Form>;
}

export interface SplitOptions {
  minLength?: number;
  follow?: boolean;
  insensitive?: boolean;
}

export interface Token {
  lemma: string;
  language?: string;
  entries: Array<LookupResult>;
  kind: string;
  script: string;
  start: number;
  end: number;
}

export interface TokenizeOptions {
  follow?: boolean;
  allowList?: Array<string>;
  insensitive?: boolean;
}

export interface Translation {
  lang: string;
  value: string;
}
