["build:node"]
run = "pnpm --filter=\"@odict/node\" build"

["publish:node"]
run = "pnpm --filter=\"@odict/node\" npm publish"

["test:node"]
depends = ["build:node"]
run = "pnpm --filter=\"@odict/node\" test -- "

["ci:node"]
run = 'act napi --container-architecture linux/amd64 --bind --job {{arg(name="job_id")}}'
hide = true

["clean:node"]
run = "rm -f bindings/node/*.node bindings/node/index.d.ts bindings/node/index.js bindings/node/browser.js bindings/node/*-worker.mjs bindings/node/*-worker-browser.mjs bindings/node/*.wasi.cjs bindings/node/*.wasi-browser.js"
