// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum POS : sbyte
{
  v = 0,
  n = 1,
  adj = 2,
  pro = 3,
  adv = 4,
  prep = 5,
  conj = 6,
  intj = 7,
  pref = 8,
  suff = 9,
  part = 10,
  art = 11,
  un = 12,
};


}
