// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type POS int8

const (
	POSv    POS = 0
	POSn    POS = 1
	POSadj  POS = 2
	POSpro  POS = 3
	POSadv  POS = 4
	POSprep POS = 5
	POSconj POS = 6
	POSintj POS = 7
	POSpref POS = 8
	POSsuff POS = 9
	POSpart POS = 10
	POSart  POS = 11
	POSun   POS = 12
)

var EnumNamesPOS = map[POS]string{
	POSv:    "v",
	POSn:    "n",
	POSadj:  "adj",
	POSpro:  "pro",
	POSadv:  "adv",
	POSprep: "prep",
	POSconj: "conj",
	POSintj: "intj",
	POSpref: "pref",
	POSsuff: "suff",
	POSpart: "part",
	POSart:  "art",
	POSun:   "un",
}

var EnumValuesPOS = map[string]POS{
	"v":    POSv,
	"n":    POSn,
	"adj":  POSadj,
	"pro":  POSpro,
	"adv":  POSadv,
	"prep": POSprep,
	"conj": POSconj,
	"intj": POSintj,
	"pref": POSpref,
	"suff": POSsuff,
	"part": POSpart,
	"art":  POSart,
	"un":   POSun,
}

func (v POS) String() string {
	if s, ok := EnumNamesPOS[v]; ok {
		return s
	}
	return "POS(" + strconv.FormatInt(int64(v), 10) + ")"
}
