use std::collections::HashSet;
use std::fmt::Write;
use std::path::Path;

use anyhow::Result;
use clap::{Arg, ArgAction, Command, CommandFactory};
use odict_cli::CLI;

pub fn generate_docs(output_path: impl AsRef<Path>) -> Result<()> {
    let mut command = CLI::command();
    command.build();

    let markdown = command_to_markdown(&command);
    std::fs::write(output_path, markdown)?;

    Ok(())
}

fn command_to_markdown(command: &Command) -> String {
    let mut output = String::new();

    output.push_str("---\n");
    output.push_str("title: CLI Reference\n");
    output.push_str("description: Complete reference for the ODict command-line interface.\n");
    output.push_str("---\n\n");
    output.push_str(
        "<!-- This file is auto-generated by `mise docgen` - do not edit manually. -->\n\n",
    );

    push_usage(&mut output, command, command.get_name());

    output.push_str(
        "The ODict CLI is the primary tool for creating, compiling, and querying ODict dictionaries.\n\n",
    );

    push_global_options(&mut output, command);

    output.push_str("---\n\n");
    output.push_str("## Commands\n\n");

    for subcommand in visible_subcommands(command) {
        push_command(
            &mut output,
            subcommand,
            &command_path(command, subcommand),
            3,
        );
        output.push_str("---\n\n");
    }

    while output.ends_with("\n\n") {
        output.pop();
    }

    output
}

fn push_global_options(output: &mut String, command: &Command) {
    output.push_str("## Global options\n\n");
    output.push_str("| Option | Description |\n");
    output.push_str("|--------|-------------|\n");

    for option in option_args(command) {
        let _ = writeln!(
            output,
            "| {} | {} |",
            format_option(option),
            format_description(option)
        );
    }

    output.push_str("| `-h, --help` | Print help |\n");
    output.push_str("| `-V, --version` | Print version |\n\n");
}

fn push_command(output: &mut String, command: &Command, path: &str, heading_level: usize) {
    let _ = writeln!(
        output,
        "{} `{}`\n",
        heading(heading_level),
        path.strip_prefix("odict ").unwrap_or(path)
    );

    if let Some(about) = command_about(command) {
        let _ = writeln!(output, "{}\n", ensure_sentence(&about));
    }

    push_usage(output, command, path);
    push_positionals(output, command, heading_level + 1);
    push_options(output, command, heading_level + 1);

    if command.get_name() == "serve" {
        push_serve_endpoints(output, heading_level + 1);
    }

    for subcommand in visible_subcommands(command) {
        let subcommand_path = format!("{path} {}", subcommand.get_name());
        push_command(output, subcommand, &subcommand_path, heading_level + 1);
    }
}

fn push_usage(output: &mut String, command: &Command, path: &str) {
    let mut command = command.clone().bin_name(path);
    let usage = command.render_usage().to_string();
    let usage = usage.strip_prefix("Usage: ").unwrap_or(&usage);

    let _ = writeln!(output, "```\n{usage}\n```\n");
}

fn push_positionals(output: &mut String, command: &Command, heading_level: usize) {
    let positionals: Vec<_> = command.get_positionals().collect();

    if positionals.is_empty() {
        return;
    }

    let _ = writeln!(output, "{} Arguments\n", heading(heading_level));
    output.push_str("| Argument | Required | Description |\n");
    output.push_str("|----------|----------|-------------|\n");

    for arg in positionals {
        let _ = writeln!(
            output,
            "| `{}` | {} | {} |",
            display_arg_name(arg),
            if arg.is_required_set() { "Yes" } else { "No" },
            format_description(arg)
        );
    }

    output.push('\n');
}

fn push_options(output: &mut String, command: &Command, heading_level: usize) {
    let options = option_args(command);

    if options.is_empty() {
        return;
    }

    let _ = writeln!(output, "{} Options\n", heading(heading_level));
    output.push_str("| Flag | Description |\n");
    output.push_str("|------|-------------|\n");

    for option in options {
        let _ = writeln!(
            output,
            "| {} | {} |",
            format_option(option),
            format_description(option)
        );
    }

    output.push('\n');
}

fn push_serve_endpoints(output: &mut String, heading_level: usize) {
    let endpoints_level = heading_level + 1;

    let _ = writeln!(output, "{} HTTP endpoints\n", heading(heading_level));
    output.push_str(
        "When running `serve`, the following REST endpoints become available. All return JSON.\n\n",
    );

    let _ = writeln!(
        output,
        "{} `GET /{{name}}/lookup`\n",
        heading(endpoints_level)
    );
    output.push_str("| Parameter | Type | Required | Description |\n");
    output.push_str("|-----------|------|----------|-------------|\n");
    output.push_str("| `q` | string | Yes | Term or comma-separated terms to look up |\n");
    output.push_str("| `follow` | boolean | No | Follow `see` cross-references |\n");
    output.push_str(
        "| `split` | number | No | Minimum character length for fallback splitting |\n\n",
    );

    let _ = writeln!(
        output,
        "{} `GET /{{name}}/search`\n",
        heading(endpoints_level)
    );
    output.push_str("| Parameter | Type | Required | Description |\n");
    output.push_str("|-----------|------|----------|-------------|\n");
    output.push_str("| `q` | string | Yes | Full-text search query |\n");
    output.push_str("| `limit` | number | No | Maximum number of results |\n\n");

    let _ = writeln!(
        output,
        "{} `GET /{{name}}/split`\n",
        heading(endpoints_level)
    );
    output.push_str("| Parameter | Type | Required | Description |\n");
    output.push_str("|-----------|------|----------|-------------|\n");
    output.push_str("| `q` | string | Yes | Term or comma-separated terms to split |\n");
    output.push_str("| `follow` | boolean | No | Follow `see` cross-references |\n");
    output
        .push_str("| `min_length` | number | No | Minimum character length for each segment |\n\n");

    let _ = writeln!(
        output,
        "{} `GET /{{name}}/tokenize`\n",
        heading(endpoints_level)
    );
    output.push_str("| Parameter | Type | Required | Description |\n");
    output.push_str("|-----------|------|----------|-------------|\n");
    output.push_str("| `text` | string | Yes | Text to tokenize |\n");
    output.push_str(
        "| `follow` | boolean | No | Follow `see` cross-references for matched tokens |\n\n",
    );
}

fn option_args(command: &Command) -> Vec<&Arg> {
    let positional_ids: HashSet<_> = command
        .get_positionals()
        .map(|arg| arg.get_id().as_str())
        .collect();

    command
        .get_arguments()
        .filter(|arg| {
            !positional_ids.contains(arg.get_id().as_str())
                && !is_generated_help_or_version(arg)
                && (arg.get_short().is_some() || arg.get_long().is_some())
        })
        .collect()
}

fn is_generated_help_or_version(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Help | ArgAction::Version)
}

fn visible_subcommands(command: &Command) -> impl Iterator<Item = &Command> {
    command
        .get_subcommands()
        .filter(|subcommand| !subcommand.is_hide_set() && subcommand.get_name() != "help")
}

fn format_option(arg: &Arg) -> String {
    let value = option_value_suffix(arg);
    let mut names = Vec::new();

    if let Some(short) = arg.get_short() {
        names.push(format!("-{short}{value}"));
    }

    if let Some(long) = arg.get_long() {
        names.push(format!("--{long}{value}"));
    }

    format!("`{}`", names.join(", "))
}

fn option_value_suffix(arg: &Arg) -> String {
    if !takes_value(arg) {
        return String::new();
    }

    format!(" <{}>", value_name(arg))
}

fn takes_value(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Set | ArgAction::Append)
}

fn value_name(arg: &Arg) -> String {
    arg.get_value_names()
        .and_then(|names| names.first())
        .map(ToString::to_string)
        .unwrap_or_else(|| display_arg_name(arg).to_ascii_uppercase())
}

fn format_description(arg: &Arg) -> String {
    let mut description = arg
        .get_help()
        .or_else(|| arg.get_long_help())
        .map(ToString::to_string)
        .unwrap_or_default();

    description = normalize_whitespace(&description);

    let defaults: Vec<_> = if matches!(arg.get_action(), ArgAction::SetTrue | ArgAction::SetFalse) {
        Vec::new()
    } else {
        arg.get_default_values()
            .iter()
            .map(|value| format!("`{}`", value.to_string_lossy()))
            .collect()
    };

    if !defaults.is_empty() {
        if !description.is_empty() {
            description.push(' ');
        }
        let _ = write!(description, "(default: {})", defaults.join(", "));
    }

    escape_table_cell(&description)
}

fn command_about(command: &Command) -> Option<String> {
    command
        .get_about()
        .or_else(|| command.get_long_about())
        .map(ToString::to_string)
        .map(|about| normalize_whitespace(&about))
        .filter(|about| !about.is_empty())
}

fn display_arg_name(arg: &Arg) -> String {
    arg.get_id().as_str().replace('-', "_")
}

fn command_path(root: &Command, subcommand: &Command) -> String {
    format!("{} {}", root.get_name(), subcommand.get_name())
}

fn heading(level: usize) -> &'static str {
    const HASHES: [&str; 6] = ["#", "##", "###", "####", "#####", "######"];
    HASHES[level.clamp(1, 6) - 1]
}

fn normalize_whitespace(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn ensure_sentence(value: &str) -> String {
    if value.ends_with(['.', '!', '?']) {
        value.to_string()
    } else {
        format!("{value}.")
    }
}

fn escape_table_cell(value: &str) -> String {
    value.replace('|', "\\|")
}
