use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::path::Path;

use anyhow::{Context, Result, bail};
use odict::schema::{
    Definition, DefinitionType, Dictionary, Entry, EntryRef, EntrySet, Etymology, Example, Form,
    FormKind, Group, MediaURL, Note, PartOfSpeech, Pronunciation, PronunciationKind, Sense,
    SenseSet, Translation,
};
use serde_reflection::{
    ContainerFormat, Error as ReflectionError, Format, Named, Registry, Samples, Tracer,
    TracerConfig, VariantFormat,
};

pub fn generate_schema(output_path: impl AsRef<Path>) -> Result<()> {
    let schema = render_schema()?;
    let output_path = output_path.as_ref();

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent).with_context(|| {
            format!(
                "failed to create schema output directory {}",
                parent.display()
            )
        })?;
    }

    std::fs::write(output_path, schema)
        .with_context(|| format!("failed to write schema to {}", output_path.display()))?;

    Ok(())
}

fn render_schema() -> Result<String> {
    let registry = trace_schema()?;
    let mut output = String::new();
    let mut emitted = BTreeSet::new();

    output.push_str(
        "<xs:schema attributeFormDefault=\"unqualified\" elementFormDefault=\"qualified\"\n",
    );
    output.push_str("  xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n");
    output.push_str(
        "  <!-- This file is auto-generated by `mise docgen` - do not edit manually. -->\n\n",
    );

    for &name in preferred_type_order() {
        if let Some(container) = registry.get(name)
            && should_emit_complex_type(container)
        {
            write_complex_type(&mut output, name, container, &registry)?;
            emitted.insert(name.to_string());
        }
    }

    for (name, container) in &registry {
        if emitted.contains(name) || !should_emit_complex_type(container) {
            continue;
        }

        write_complex_type(&mut output, name, container, &registry)?;
    }

    output.push_str("  <xs:element name=\"dictionary\" type=\"dictionaryType\"/>\n");
    output.push_str("</xs:schema>\n");

    Ok(output)
}

fn trace_schema() -> Result<Registry> {
    let mut tracer = Tracer::new(TracerConfig::default().is_human_readable(true));
    let mut samples = Samples::new();
    let sample = sample_dictionary();

    tracer
        .trace_value(&mut samples, &sample)
        .map_err(reflection_error)?;

    tracer.registry().map_err(reflection_error)
}

fn sample_dictionary() -> Dictionary {
    let definition = Definition {
        id: Some("definition-id".to_string()),
        value: "definition".to_string(),
        examples: vec![Example {
            value: "example".to_string(),
            translations: vec![Translation {
                lang: "en".to_string(),
                value: "translation".to_string(),
            }],
            pronunciations: vec![Pronunciation {
                kind: Some(PronunciationKind::IPA),
                value: "pronunciation".to_string(),
                media: vec![media_url("./example.mp3")],
            }],
        }],
        notes: vec![Note {
            examples: vec![Example {
                value: "note example".to_string(),
                translations: vec![Translation {
                    lang: "en".to_string(),
                    value: "note translation".to_string(),
                }],
                pronunciations: vec![Pronunciation {
                    kind: Some(PronunciationKind::IPA),
                    value: "note pronunciation".to_string(),
                    media: vec![media_url("./note.mp3")],
                }],
            }],
            id: Some("note-id".to_string()),
            value: "note".to_string(),
        }],
    };

    let mut senses = SenseSet::new();
    senses.insert(Sense {
        pos: PartOfSpeech::N,
        lemma: Some(EntryRef::new("lemma")),
        definitions: vec![
            DefinitionType::Group(Group {
                id: Some("group-id".to_string()),
                description: "group".to_string(),
                definitions: vec![definition.clone()],
            }),
            DefinitionType::Definition(definition),
        ],
        tags: vec!["tag".to_string()],
        translations: vec![Translation {
            lang: "en".to_string(),
            value: "sense translation".to_string(),
        }],
        forms: vec![Form {
            kind: Some(FormKind::Plural),
            term: EntryRef::new("terms"),
            tags: vec!["plural".to_string()],
        }],
    });

    let mut entries = EntrySet::new();
    entries.insert(Entry {
        term: "term".to_string(),
        see_also: Some(EntryRef::new("see")),
        etymologies: vec![Etymology {
            id: Some("ety-id".to_string()),
            pronunciations: vec![Pronunciation {
                kind: Some(PronunciationKind::IPA),
                value: "ety pronunciation".to_string(),
                media: vec![media_url("./ety.mp3")],
            }],
            senses,
            description: Some("etymology".to_string()),
        }],
        media: vec![media_url("./media.png")],
        rank: Some(1),
    });

    Dictionary {
        id: Default::default(),
        name: Some("Sample Dictionary".to_string()),
        entries,
    }
}

fn media_url(src: &str) -> MediaURL {
    MediaURL {
        src: src.to_string(),
        mime_type: Some("application/octet-stream".to_string()),
        description: Some("media".to_string()),
    }
}

fn reflection_error(error: ReflectionError) -> anyhow::Error {
    anyhow::anyhow!("{}\n{}", error, error.explanation().trim())
}

fn preferred_type_order() -> &'static [&'static str] {
    &[
        "url",
        "Pronunciation",
        "translation",
        "example",
        "note",
        "Definition",
        "group",
        "form",
        "sense",
        "ety",
        "entry",
        "dictionary",
    ]
}

fn should_emit_complex_type(container: &ContainerFormat) -> bool {
    matches!(container, ContainerFormat::Struct(_))
}

fn write_complex_type(
    output: &mut String,
    name: &str,
    container: &ContainerFormat,
    registry: &Registry,
) -> Result<()> {
    let ContainerFormat::Struct(fields) = container else {
        return Ok(());
    };

    let child_fields: Vec<_> = fields.iter().filter(|field| !is_attribute(field)).collect();

    let _ = writeln!(
        output,
        "  <xs:complexType name=\"{}\">",
        xsd_type_name(name)
    );

    if !child_fields.is_empty() {
        output.push_str("    <xs:sequence>\n");
        for field in child_fields {
            write_child_field(output, field, registry)?;
        }
        output.push_str("    </xs:sequence>\n");
    }

    for field in fields.iter().filter(|field| is_attribute(field)) {
        write_attribute(output, name, field, registry)?;
    }

    output.push_str("  </xs:complexType>\n\n");

    Ok(())
}

fn write_child_field(
    output: &mut String,
    field: &Named<Format>,
    registry: &Registry,
) -> Result<()> {
    if field.name == "$value" {
        return write_value_field(output, &field.value, registry);
    }

    let (format, min_occurs, max_occurs) = element_occurrence(&field.value);
    let element_type = xsd_format_type(format, registry)?;

    let _ = writeln!(
        output,
        "      <xs:element name=\"{}\" type=\"{}\" minOccurs=\"{}\" maxOccurs=\"{}\"/>",
        field.name, element_type, min_occurs, max_occurs
    );

    Ok(())
}

fn write_value_field(output: &mut String, format: &Format, registry: &Registry) -> Result<()> {
    let (format, min_occurs, max_occurs) = element_occurrence(format);
    let Format::TypeName(type_name) = format else {
        bail!("unsupported $value field format: {format:?}");
    };

    let Some(ContainerFormat::Enum(variants)) = registry.get(type_name) else {
        bail!("unsupported $value type: {type_name}");
    };

    let _ = writeln!(
        output,
        "      <xs:choice minOccurs=\"{}\" maxOccurs=\"{}\">",
        min_occurs, max_occurs
    );

    for variant in variants.values() {
        write_choice_variant(output, variant, registry)?;
    }

    output.push_str("      </xs:choice>\n");

    Ok(())
}

fn write_choice_variant(
    output: &mut String,
    variant: &Named<VariantFormat>,
    registry: &Registry,
) -> Result<()> {
    let element_type = match &variant.value {
        VariantFormat::NewType(format) => xsd_format_type(format, registry)?,
        other => bail!("unsupported XML choice variant {}: {other:?}", variant.name),
    };

    let _ = writeln!(
        output,
        "        <xs:element name=\"{}\" type=\"{}\"/>",
        variant.name, element_type
    );

    Ok(())
}

fn write_attribute(
    output: &mut String,
    parent_name: &str,
    field: &Named<Format>,
    registry: &Registry,
) -> Result<()> {
    let attribute_name = field.name.trim_start_matches('@');
    let attribute_type = xsd_format_type(strip_option(&field.value), registry)?;
    let use_attribute = if is_required_attribute(parent_name, field) {
        " use=\"required\""
    } else {
        ""
    };

    let _ = writeln!(
        output,
        "    <xs:attribute name=\"{}\" type=\"{}\"{}/>",
        attribute_name, attribute_type, use_attribute
    );

    Ok(())
}

fn is_required_attribute(parent_name: &str, field: &Named<Format>) -> bool {
    !matches!(field.value, Format::Option(_)) && !is_defaulted_attribute(parent_name, &field.name)
}

fn is_defaulted_attribute(parent_name: &str, field_name: &str) -> bool {
    matches!(
        (parent_name, field_name),
        ("Dictionary" | "dictionary", "@id") | ("Sense" | "sense", "@pos")
    )
}

fn element_occurrence(format: &Format) -> (&Format, &'static str, &'static str) {
    match format {
        Format::Option(inner) => (inner, "0", "1"),
        Format::Seq(inner) => (inner, "0", "unbounded"),
        _ => (format, "1", "1"),
    }
}

fn strip_option(format: &Format) -> &Format {
    match format {
        Format::Option(inner) => inner,
        _ => format,
    }
}

fn xsd_format_type(format: &Format, registry: &Registry) -> Result<String> {
    match format {
        Format::Bool => Ok("xs:boolean".to_string()),
        Format::I8 | Format::I16 | Format::I32 | Format::I64 | Format::I128 => {
            Ok("xs:integer".to_string())
        }
        Format::U8 | Format::U16 => Ok("xs:unsignedShort".to_string()),
        Format::U32 => Ok("xs:unsignedInt".to_string()),
        Format::U64 | Format::U128 => Ok("xs:unsignedLong".to_string()),
        Format::F32 | Format::F64 => Ok("xs:decimal".to_string()),
        Format::Char | Format::Str => Ok("xs:string".to_string()),
        Format::Option(inner) | Format::Seq(inner) => xsd_format_type(inner, registry),
        Format::TypeName(type_name) => xsd_type_reference(type_name, registry),
        other => bail!("unsupported XSD format: {other:?}"),
    }
}

fn xsd_type_reference(type_name: &str, registry: &Registry) -> Result<String> {
    let Some(container) = registry.get(type_name) else {
        bail!("unknown schema type: {type_name}");
    };

    match container {
        ContainerFormat::NewTypeStruct(format) => xsd_format_type(format, registry),
        ContainerFormat::Enum(variants) if is_open_string_enum(variants) => {
            Ok("xs:string".to_string())
        }
        ContainerFormat::Struct(_) => Ok(xsd_type_name(type_name)),
        ContainerFormat::Enum(_) => Ok("xs:string".to_string()),
        other => bail!("unsupported schema type {type_name}: {other:?}"),
    }
}

fn is_open_string_enum(variants: &BTreeMap<u32, Named<VariantFormat>>) -> bool {
    variants.values().any(|variant| {
        variant.name == "Other"
            && matches!(variant.value, VariantFormat::NewType(ref format) if **format == Format::Str)
    })
}

fn is_attribute(field: &Named<Format>) -> bool {
    field.name.starts_with('@')
}

fn xsd_type_name(name: &str) -> String {
    match name {
        "MediaURL" => "mediaUrlType".to_string(),
        _ => format!("{}Type", lower_camel(name)),
    }
}

fn lower_camel(name: &str) -> String {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };

    let mut output = String::new();
    output.push(first.to_ascii_lowercase());
    output.extend(chars);
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_schema_contains_current_xml_model() {
        let schema = render_schema().unwrap();

        assert!(schema.contains("<xs:element name=\"media\" type=\"urlType\""));
        assert!(schema.contains("<xs:attribute name=\"rank\" type=\"xs:unsignedInt\""));
        assert!(schema.contains("<xs:attribute name=\"lemma\" type=\"xs:string\""));
        assert!(schema.contains("<xs:element name=\"translation\" type=\"translationType\""));
        assert!(schema.contains("<xs:element name=\"form\" type=\"formType\""));
        assert!(schema.contains("<xs:attribute name=\"id\" type=\"xs:string\"/>"));
        assert!(schema.contains("<xs:attribute name=\"pos\" type=\"xs:string\"/>"));
    }
}
