[package]
name = "pyodict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyodict"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.1", features = ["either", "serde"] }
odict = { path = "../lib", features = ["config", "sql", "search", "json"] }
either = { version = "*", features = ["serde"] }
serde = "1.0.216"
