[package]
name = "odict_python"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "theopendictionary"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.0", features = ["either"] }
odict = { path = "../lib", features = [
  "config",
  "sql",
  "tokenize",
  "search",
  "json",
] }
either = { version = "*" }
