[package]
name = "odict_python"
version = "1.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "theopendictionary"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["either"] }
odict = { path = "../lib", features = ["config", "sql", "tokenize", "search"] }
internal = { path = "../internal" }
either = { version = "*" }
structural-convert = { workspace = true }
