install: update
	poetry install 

test: install && clean
  just ../build
  RUNTIME_ENV=test poetry run pytest ./theopendictionary

clean:
  rm -rf *.odict ../**/*.odict .pytest_cache **/__pycache__ **/*.pyc

update:
	poetry update 

build: install
	poetry build

publish: build
	poetry publish
