[tools]
python = "3.14.3"
uv = "latest"

[deps.uv]
auto = true

[tasks.dev]
run = "uvx maturin develop -m ./Cargo.toml"
sources = ["src/**/*.rs", "Cargo.toml"]
outputs = { auto = true }

[tasks.build]
run = "uvx maturin build -m ./Cargo.toml"
outputs = { auto = true }
sources = ["src/**/*.rs", "Cargo.toml"]

[tasks.lint]
run = "ruff check"

[tasks."generate-ci"]
run = "uvx maturin generate-ci  -o ../../.github/workflows/python.yml -m ./Cargo.toml --pytest github"

[tasks.format]
run = ["cargo fmt", "ruff format"]
sources = ["src/**/*.rs", "src/**/*.py"]
outputs = { auto = true }

[tasks.snapshot]
depends = [":test --snapshot-update"]

[tasks.test]
run = "uvx --with syrupy --with pytest-asyncio --with . --refresh pytest -vv"
