["dev:python"]
run = "uv tool run maturin develop -m ${MISE_TASK_DIR}/Cargo.toml"
sources = ["python/src/**/*.rs", "python/Cargo.toml"]
outputs = { auto = true }

["build:python"]
run = "uv tool run maturin build -m ${MISE_TASK_DIR}/Cargo.toml"
outputs = { auto = true }
sources = ["python/src/**/*.rs", "python/Cargo.toml"]

["lint:python"]
run = "uv tool run ruff check"

["format:python"]
run = "uv --preview-features format format"

["snapshot:python"]
run = "uv tool run pytest --snapshot-update"
depends = ["dev:python"]

["test:python"]
run = ".venv/bin/pytest -vv"
depends = ["dev:python"]
