["dev:python"]
run = "uv tool run maturin develop -m ${MISE_TASK_DIR}/Cargo.toml"
sources = ["python/src/**/*.rs", "python/Cargo.toml"]
outputs = { auto = true }

["build:python"]
run = "uv tool run maturin build -m ${MISE_TASK_DIR}/Cargo.toml"
outputs = { auto = true }
sources = ["python/src/**/*.rs", "python/Cargo.toml"]

["lint:python"]
run = "uv tool run ruff check"

["generate-ci:python"]
run = "uv tool run maturin generate-ci  -o .github/workflows/python.yml -m python/Cargo.toml --pytest github"

["format:python"]
run = "uv --preview-features format format"

["snapshot:python"]
run = "mise run test:python --snapshot-update"

["test:python"]
run = "uv tool run -w syrupy -w pytest-asyncio -w ./python --refresh pytest -vv"
