["dev:python"]
run = "maturin develop"
dir = "python"

["build:python"]
run = "maturin build"
dir = "python"

["format:python"]
run = "black ."
dir = "python"

["lint:python"]
run = "flake8"
dir = "python"

["snapshot:python"]
run = ".venv/bin/pytest --snapshot-update"
depends = ["dev:python"]

["test:python"]
run = ".venv/bin/pytest -vv"
depends = ["dev:python"]

["generate-ci:python"]
description = "Generate GitHub Actions CI workflow for Python"
run = "maturin generate-ci github -m python/Cargo.toml -o .github/workflows/python.yml --pytest"

["setup:python"]
run = "pip install -r requirements.txt"
dir = "python"
