[package]
name = "internal"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
odict = { path = "../lib", features = [] }
strum = { version = "0.27.1", features = ["derive"] }

[lib]
name = "internal"
crate-type = ["cdylib", "staticlib", "lib"]
