// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_
#define FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

namespace schema {

struct Etymology;

struct Group;

struct Usage;

struct Entry;

struct Dictionary;

enum POS {
  POS_verb = 0,
  POS_noun = 1,
  POS_adj = 2,
  POS_pronoun = 3,
  POS_adv = 4,
  POS_prep = 5,
  POS_conj = 6,
  POS_intj = 7,
  POS_prefix = 8,
  POS_suffix = 9,
  POS_particle = 10,
  POS_MIN = POS_verb,
  POS_MAX = POS_particle
};

inline POS (&EnumValuesPOS())[11] {
  static POS values[] = {
    POS_verb,
    POS_noun,
    POS_adj,
    POS_pronoun,
    POS_adv,
    POS_prep,
    POS_conj,
    POS_intj,
    POS_prefix,
    POS_suffix,
    POS_particle
  };
  return values;
}

inline const char **EnumNamesPOS() {
  static const char *names[] = {
    "verb",
    "noun",
    "adj",
    "pronoun",
    "adv",
    "prep",
    "conj",
    "intj",
    "prefix",
    "suffix",
    "particle",
    nullptr
  };
  return names;
}

inline const char *EnumNamePOS(POS e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesPOS()[index];
}

struct Etymology FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_DESCRIPTION = 6,
    VT_USAGES = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Usage>> *usages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Usage>> *>(VT_USAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.Verify(description()) &&
           VerifyOffset(verifier, VT_USAGES) &&
           verifier.Verify(usages()) &&
           verifier.VerifyVectorOfTables(usages()) &&
           verifier.EndTable();
  }
};

struct EtymologyBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Etymology::VT_ID, id, 0);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(Etymology::VT_DESCRIPTION, description);
  }
  void add_usages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Usage>>> usages) {
    fbb_.AddOffset(Etymology::VT_USAGES, usages);
  }
  explicit EtymologyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  EtymologyBuilder &operator=(const EtymologyBuilder &);
  flatbuffers::Offset<Etymology> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Etymology>(end);
    return o;
  }
};

inline flatbuffers::Offset<Etymology> CreateEtymology(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Usage>>> usages = 0) {
  EtymologyBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_usages(usages);
  builder_.add_description(description);
  return builder_.Finish();
}

inline flatbuffers::Offset<Etymology> CreateEtymologyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *description = nullptr,
    const std::vector<flatbuffers::Offset<Usage>> *usages = nullptr) {
  return schema::CreateEtymology(
      _fbb,
      id,
      description ? _fbb.CreateString(description) : 0,
      usages ? _fbb.CreateVector<flatbuffers::Offset<Usage>>(*usages) : 0);
}

struct Group FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_DESCRIPTION = 6,
    VT_DEFINITIONS = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *definitions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_DEFINITIONS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.Verify(description()) &&
           VerifyOffset(verifier, VT_DEFINITIONS) &&
           verifier.Verify(definitions()) &&
           verifier.VerifyVectorOfStrings(definitions()) &&
           verifier.EndTable();
  }
};

struct GroupBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Group::VT_ID, id, 0);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(Group::VT_DESCRIPTION, description);
  }
  void add_definitions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> definitions) {
    fbb_.AddOffset(Group::VT_DEFINITIONS, definitions);
  }
  explicit GroupBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  GroupBuilder &operator=(const GroupBuilder &);
  flatbuffers::Offset<Group> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Group>(end);
    return o;
  }
};

inline flatbuffers::Offset<Group> CreateGroup(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> definitions = 0) {
  GroupBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_definitions(definitions);
  builder_.add_description(description);
  return builder_.Finish();
}

inline flatbuffers::Offset<Group> CreateGroupDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *description = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *definitions = nullptr) {
  return schema::CreateGroup(
      _fbb,
      id,
      description ? _fbb.CreateString(description) : 0,
      definitions ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*definitions) : 0);
}

struct Usage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_POS = 6,
    VT_DEFINITIONS = 8,
    VT_GROUPS = 10
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const flatbuffers::String *pos() const {
    return GetPointer<const flatbuffers::String *>(VT_POS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *definitions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_DEFINITIONS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Group>> *groups() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Group>> *>(VT_GROUPS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_POS) &&
           verifier.Verify(pos()) &&
           VerifyOffset(verifier, VT_DEFINITIONS) &&
           verifier.Verify(definitions()) &&
           verifier.VerifyVectorOfStrings(definitions()) &&
           VerifyOffset(verifier, VT_GROUPS) &&
           verifier.Verify(groups()) &&
           verifier.VerifyVectorOfTables(groups()) &&
           verifier.EndTable();
  }
};

struct UsageBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Usage::VT_ID, id, 0);
  }
  void add_pos(flatbuffers::Offset<flatbuffers::String> pos) {
    fbb_.AddOffset(Usage::VT_POS, pos);
  }
  void add_definitions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> definitions) {
    fbb_.AddOffset(Usage::VT_DEFINITIONS, definitions);
  }
  void add_groups(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Group>>> groups) {
    fbb_.AddOffset(Usage::VT_GROUPS, groups);
  }
  explicit UsageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UsageBuilder &operator=(const UsageBuilder &);
  flatbuffers::Offset<Usage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Usage>(end);
    return o;
  }
};

inline flatbuffers::Offset<Usage> CreateUsage(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    flatbuffers::Offset<flatbuffers::String> pos = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> definitions = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Group>>> groups = 0) {
  UsageBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_groups(groups);
  builder_.add_definitions(definitions);
  builder_.add_pos(pos);
  return builder_.Finish();
}

inline flatbuffers::Offset<Usage> CreateUsageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *pos = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *definitions = nullptr,
    const std::vector<flatbuffers::Offset<Group>> *groups = nullptr) {
  return schema::CreateUsage(
      _fbb,
      id,
      pos ? _fbb.CreateString(pos) : 0,
      definitions ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*definitions) : 0,
      groups ? _fbb.CreateVector<flatbuffers::Offset<Group>>(*groups) : 0);
}

struct Entry FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_TERM = 6,
    VT_ETYMOLOGIES = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const flatbuffers::String *term() const {
    return GetPointer<const flatbuffers::String *>(VT_TERM);
  }
  bool KeyCompareLessThan(const Entry *o) const {
    return *term() < *o->term();
  }
  int KeyCompareWithValue(const char *val) const {
    return strcmp(term()->c_str(), val);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Etymology>> *etymologies() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Etymology>> *>(VT_ETYMOLOGIES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyOffsetRequired(verifier, VT_TERM) &&
           verifier.Verify(term()) &&
           VerifyOffset(verifier, VT_ETYMOLOGIES) &&
           verifier.Verify(etymologies()) &&
           verifier.VerifyVectorOfTables(etymologies()) &&
           verifier.EndTable();
  }
};

struct EntryBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Entry::VT_ID, id, 0);
  }
  void add_term(flatbuffers::Offset<flatbuffers::String> term) {
    fbb_.AddOffset(Entry::VT_TERM, term);
  }
  void add_etymologies(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Etymology>>> etymologies) {
    fbb_.AddOffset(Entry::VT_ETYMOLOGIES, etymologies);
  }
  explicit EntryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  EntryBuilder &operator=(const EntryBuilder &);
  flatbuffers::Offset<Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Entry>(end);
    fbb_.Required(o, Entry::VT_TERM);
    return o;
  }
};

inline flatbuffers::Offset<Entry> CreateEntry(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    flatbuffers::Offset<flatbuffers::String> term = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Etymology>>> etymologies = 0) {
  EntryBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_etymologies(etymologies);
  builder_.add_term(term);
  return builder_.Finish();
}

inline flatbuffers::Offset<Entry> CreateEntryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *term = nullptr,
    const std::vector<flatbuffers::Offset<Etymology>> *etymologies = nullptr) {
  return schema::CreateEntry(
      _fbb,
      id,
      term ? _fbb.CreateString(term) : 0,
      etymologies ? _fbb.CreateVector<flatbuffers::Offset<Etymology>>(*etymologies) : 0);
}

struct Dictionary FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_NAME = 6,
    VT_ENTRIES = 8
  };
  const flatbuffers::String *id() const {
    return GetPointer<const flatbuffers::String *>(VT_ID);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Entry>> *entries() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Entry>> *>(VT_ENTRIES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.Verify(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.Verify(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct DictionaryBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(flatbuffers::Offset<flatbuffers::String> id) {
    fbb_.AddOffset(Dictionary::VT_ID, id);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Dictionary::VT_NAME, name);
  }
  void add_entries(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Entry>>> entries) {
    fbb_.AddOffset(Dictionary::VT_ENTRIES, entries);
  }
  explicit DictionaryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DictionaryBuilder &operator=(const DictionaryBuilder &);
  flatbuffers::Offset<Dictionary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Dictionary>(end);
    return o;
  }
};

inline flatbuffers::Offset<Dictionary> CreateDictionary(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> id = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Entry>>> entries = 0) {
  DictionaryBuilder builder_(_fbb);
  builder_.add_entries(entries);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Dictionary> CreateDictionaryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<Entry>> *entries = nullptr) {
  return schema::CreateDictionary(
      _fbb,
      id ? _fbb.CreateString(id) : 0,
      name ? _fbb.CreateString(name) : 0,
      entries ? _fbb.CreateVector<flatbuffers::Offset<Entry>>(*entries) : 0);
}

inline const schema::Dictionary *GetDictionary(const void *buf) {
  return flatbuffers::GetRoot<schema::Dictionary>(buf);
}

inline bool VerifyDictionaryBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<schema::Dictionary>(nullptr);
}

inline void FinishDictionaryBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<schema::Dictionary> root) {
  fbb.Finish(root);
}

}  // namespace schema

#endif  // FLATBUFFERS_GENERATED_SCHEMA_SCHEMA_H_
