name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: ${{ github.event_name != 'release' || startsWith(github.event.release.tag_name, 'cli/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7
      - name: Install, build, and upload your site
        uses: withastro/action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: docs
          package-manager: yarn
  deploy:
    needs: build
    if: ${{ github.event_name != 'release' || startsWith(github.event.release.tag_name, 'cli/') }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
