name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "docs/**"
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: ${{ github.event_name == 'push' || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'cli/')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        working-directory: docs
        run: yarn install --immutable
      - name: Build site
        working-directory: docs
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/dist/
          include-hidden-files: true
  deploy:
    needs: build
    if: ${{ github.event_name == 'push' || (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'cli/')) }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
