name: Release crate

permissions:
  "contents": "write"

on:
  workflow_dispatch:
  push:
    tags:
      - 'lib**[0-9]+.[0-9]+.[0-9]'

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2      
      - name: Build library
        run: cargo publish -p odict
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: code
          path: /home/runner/work/odict
